export const RewardsData = [
  {
    transactionId: 1,
    customerId: "C001",
    customerName: "Arjun",
    amountSpent: 120.5,
    transactionDate: "01/11/2023",
    productPurchased: "Laptop",
  },
  {
    transactionId: 2,
    customerId: "C002",
    customerName: "Krishna",
    amountSpent: 78.25,
    transactionDate: "23/11/2023",
    productPurchased: "Shoes",
  },
  {
    transactionId: 3,
    customerId: "C002",
    customerName: "Krishna",
    amountSpent: 200.0,
    transactionDate: "12/12/2023",
    productPurchased: "Watch",
  },
  {
    transactionId: 4,
    customerId: "C003",
    customerName: "Karna",
    amountSpent: 95.7,
    transactionDate: "30/12/2023",
    productPurchased: "Bag",
  },
  {
    transactionId: 5,
    customerId: "C001",
    customerName: "Arjun",
    amountSpent: 110.85,
    transactionDate: "20/01/2024",
    productPurchased: "Mobile",
  },
];
